### ISSUE TITLE
Cursor keeps snapping to the left

### ISSUE THREAD

**Issue by wrightak** [bealex/SwiftLintAppCode#45] opened 2020-02-06 06:33 UTC
With this plugin enabled, the cursor keeps snapping to the leftmost position on each line. Beginning a new line will put the cursor to the leftmost position instead of the current tab indentation. Pressing tab to go back to where the cursor should be will be followed by another snap back to the left if I don't start typing quickly enough.

**Comment by bealex** [comment] 2020-02-09 20:19
This sounds strange and possibly like a bug in AppCode itself. I have to investigate this further.

**Comment by bealex** [comment] 2020-05-10 16:09
Can't reproduce for now. Closing.

**Closed as completed by bealex** 2020-05-10 16:09 UTC
